service: morninglightSchedules

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs4.3
  region: eu-central-1
  stage: dev
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:eu-central-1:*:*"
    - Effect: Allow
      Action:
        - sns:Publish
      Resource: "arn:aws:sns:eu-central-1:*:morninglightTopic"

custom:
  webpackIncludeModules: true

functions:
  create:
    handler: handler.create
    events:
      - http:
          path: schedules
          method: post
          integration: lambda
          cors: true

resources:
  Resources:
    schedulesTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        TableName: 'schedules'
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    morninglightTopic:
      Type: AWS::SNS::Topic
      Properties:
        DisplayName: 'Morning Light Topic'
        TopicName: morninglightTopic