service: morninglightEvents

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs4.3
  region: eu-central-1
  stage: dev
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:eu-central-1:*:*"

custom:
  webpackIncludeModules: true

functions:
  create:
    handler: handler.create
    events:
    - sns: arn:aws:sns:eu-central-1:227235672402:morninglightTopic