service: morninglight-api

plugins:
  - serverless-webpack

custom:
  webpack:
    webpackConfig: "webpack.config.js"
    includeModules: 
      forceExclude:
        - aws-sdk
    packager: "yarn"

package:
  individually: true

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: eu-central-1
  timeout: 20
  environment:
    REGION: ${self:provider.region}
    PHOTON_API_KEY: ${file(./secrets.json):PHOTON_API_KEY}
    CRON_NAME: ${self:service}-${self:provider.stage}-cron
    DYNAMODB_TABLE: ${self:service}-${self:provider.stage}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:eu-central-1:*:*"
    - Effect: "Allow"
      Action:
        - events:ListTargetsByRule
        - events:PutTargets
        - events:PutRule
        - events:PutEvents
      Resource: "*"


functions:
  executer:
    handler: handlers/executer.handler
    events:
      - schedule:
          name: ${self:provider.environment.CRON_NAME}
          rate: cron(0 0 1 1 ? 1970)
          enabled: false
  scheduler:
    handler: handlers/scheduler.handler
    events:
      - cloudwatchEvent:
          event:
            source:
              - "io.morninglight"
            detail-type:
              - "cron:executed"
              - "schedule:updated"
  schedule:
    handler: handlers/schedules.handler
    events:
      - http:
          path: schedules
          method: get
      - http:
          path: schedules/{id}
          method: get
      - http:
          path: schedules
          method: post
      - http:
          path: schedules/{id}
          method: put
      - http:
          path: schedules/{id}
          method: delete

resources:
  Resources:
    MorningLightScheduleTable:
      Type: "AWS::DynamoDB::Table"
      DeletionPolicy: "Retain"
      Properties:
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
